//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheBiletApp.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int Id { get; set; }
        public int DriverId { get; set; }
        public int TicketId { get; set; }
        public System.DateTime PurchasedDate { get; set; }
        public decimal AmountPaid { get; set; }
    
        public virtual Driver Driver { get; set; }
    }
}
