//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheBiletApp.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthToken
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string Token { get; set; }
        public System.DateTime ExpiresOn { get; set; }
        public bool IsGuard { get; set; }
        public string DeviceId { get; set; }
    
        public virtual Controller Controller { get; set; }
        public virtual Driver Driver { get; set; }
    }
}
